/* Generated by admin.html. Keep this file next to menu.html. */
const catalogoInicial = [
    ['chk-base-arroz','base','Arroz Especiado de la Casa',4500],['chk-base-crepe','base','Crepe Artesanal Francés',5900],['chk-base-pasta','base','Pasta Larga al Dente',6000],['chk-base-papasbelgas','base','Papas Belgas',8800],['chk-base-arepa','base','Arepa Antioqueña (2 uds)',4500],['chk-base-panmadre','base','Pan de Masa Madre',5800],['chk-base-omelette','base','Omelette de la Casa',5000],['chk-base-pancakes','base','Pancakes Esponjosos',6900],['chk-base-waffles','base','Waffles Artesanales',5900],
    ['chk-prot-lomo','proteina','Dados de Lomo de Res',12900],['chk-prot-pollo','proteina','Pechuga de Pollo al Grill',9900],['chk-prot-cerdo','proteina','Julianas de Cerdo',9900],['chk-salsa-bolognesa','proteina','Bolognesa de la Casa',8900],['chk-prot-huevos','proteina','Huevos Fritos',4800],['chk-prot-revueltos','proteina','Huevos Revueltos Suaves',4800],['chk-prot-salchicha','proteina','Huevos con Salchicha',6300],['chk-prot-maiz','proteina','Huevos con Maíz Tierno',5700],['chk-prot-poche','proteina','Huevos Poché',5200],
    ['chk-salsa-pomodoro','salsa','Pomodoro Napolitana',3800],['chk-salsa-champinon','salsa','Cremosa de Champiñones',4800],['chk-salsa-quesos','salsa','Fondo de Quesos Fundidos',4600],['chk-salsa-hogao','salsa','Hogao / Salsa Criolla',3900],['chk-salsa-yogurt','salsa','Yogurt Griego Natural',4300],['chk-salsa-frutos','salsa','Reducción de Frutos Rojos',4500],
    ['chk-acomp-campesino','acompanamiento','Porción de Queso Fresco',4800],['chk-prot-mozzarella','acompanamiento','Porción de Queso Mozzarella',4800],['chk-prot-chorizo','acompanamiento','Rodajas de Chorizo de cerdo',5800],['chk-acomp-ensalada','acompanamiento','Ensalada de la Casa',5300],['chk-acomp-pantostado','acompanamiento','Tajadas de Pan Tostado',3500],['chk-acomp-tocineta','acompanamiento','Tocineta Crujiente',5800],['chk-acomp-fruta','acompanamiento','Porción de Fruta de Temporada',5300],['chk-acomp-criollas','acompanamiento','Papas Criollas Fritas',5200],['chk-acomp-cascos','acompanamiento','Cascos de Papas Fritas',5500],['chk-acomp-francesa','acompanamiento','Papas a la Francesa Clásicas',5500],['chk-acomp-pure','acompanamiento','Puré de Papa Aterciopelado',5800],['chk-acomp-sabaneras','acompanamiento','Rodajas de Sabaneras Asadas',5000],['chk-acomp-caldo','acompanamiento','Caldo de Pollo',12000],['chk-acomp-cremapollo','acompanamiento','Crema de Pollo y Champiñones',12000],['chk-acomp-bowl','acompanamiento','Bowl Saludable',12000],
    ['chk-bebida-cafe','bebida','Café Negro',3800],['chk-bebida-chocolate','bebida','Chocolate Espumoso',4900],['chk-bebida-panela','bebida',"Agua'e panela Tradicional",4500],['chk-bebida-latte','bebida','Café Latte',4900],['chk-bebida-chai','bebida','Chai Latte Aromático',6900],['chk-bebida-matcha','bebida','Matcha Latte',7900],['chk-bebida-cocoa','bebida','Cocoa Cremosa',5900],['chk-bebida-infusion','bebida','Infusiones Aromáticas',4800],['chk-bebida-limonada','bebida','Limonada Cítrica Natural',5900],['chk-bebida-jamaica','bebida','Agua de Jamaica',5500],['chk-bebida-jugoagua','bebida','Jugo Natural en Agua',5900],['chk-bebida-jugoleche','bebida','Jugo Natural en Leche',6900]
];

window.menuData = {
    version: 1,
    settings: {
        discountPercent: 30,
        rates: { COP: 1, USD: 3200, EUR: 3700 }
    },
    items: catalogoInicial.map(([id, category, name, price]) => ({id, category, active: true, name: {es: name}, description: {}, price})),
    combos: [
        {id:'combo-1',active:true,name:{es:'1. Crepe de la Casa Especial'},description:{},items:['chk-base-crepe','chk-prot-pollo','chk-salsa-champinon','chk-acomp-cascos','chk-acomp-ensalada','chk-bebida-jamaica'],regularPrice:36900,discountPrice:25800},
        {id:'combo-2',active:true,name:{es:'2. Pancakes Deluxe'},description:{},items:['chk-base-pancakes','chk-prot-huevos','chk-prot-chorizo','chk-prot-mozzarella','chk-salsa-yogurt','chk-salsa-frutos','chk-acomp-fruta','chk-bebida-chocolate'],regularPrice:41300,discountPrice:28900},
        {id:'combo-3',active:true,name:{es:'4. Spaghetti Italiano Clásico'},description:{},items:['chk-base-pasta','chk-salsa-bolognesa','chk-acomp-francesa','chk-bebida-infusion'],regularPrice:25200,discountPrice:17600},
        {id:'combo-4',active:true,name:{es:'5. Papas Belgas con Toppings'},description:{},items:['chk-base-papasbelgas','chk-prot-cerdo','chk-acomp-tocineta','chk-salsa-quesos','chk-bebida-limonada'],regularPrice:35000,discountPrice:24500},
        {id:'combo-5',active:true,name:{es:'3. Omelette especial'},description:{},items:['chk-base-omelette','chk-prot-pollo','chk-prot-mozzarella','chk-prot-chorizo','chk-bebida-chocolate'],regularPrice:30400,discountPrice:21300}
    ]
};
