/* Generated by admin.html. */
window.menuData={
    "version": 1,
    "settings": {
        "discountPercent": 30,
        "rates": {
            "COP": 1,
            "USD": 3200,
            "EUR": 3700
        }
    },
    "items": [
        {
            "id": "chk-base-arroz",
            "category": "base",
            "active": true,
            "name": {
                "es": "Arroz Especiado de la Casa"
            },
            "description": {},
            "price": 4500
        },
        {
            "id": "chk-base-crepe",
            "category": "base",
            "active": true,
            "name": {
                "es": "Crepe Artesanal Francés"
            },
            "description": {},
            "price": 5900
        },
        {
            "id": "chk-base-pasta",
            "category": "base",
            "active": true,
            "name": {
                "es": "Pasta Larga al Dente"
            },
            "description": {},
            "price": 6000
        },
        {
            "id": "chk-base-papasbelgas",
            "category": "base",
            "active": true,
            "name": {
                "es": "Papas Belgas"
            },
            "description": {},
            "price": 8800
        },
        {
            "id": "chk-base-arepa",
            "category": "base",
            "active": true,
            "name": {
                "es": "Arepa Antioqueña (2 uds)"
            },
            "description": {},
            "price": 4500
        },
        {
            "id": "chk-base-panmadre",
            "category": "base",
            "active": true,
            "name": {
                "es": "Pan de Masa Madre"
            },
            "description": {},
            "price": 5800
        },
        {
            "id": "chk-base-omelette",
            "category": "base",
            "active": true,
            "name": {
                "es": "Omelette de la Casa"
            },
            "description": {},
            "price": 5000
        },
        {
            "id": "chk-base-pancakes",
            "category": "base",
            "active": true,
            "name": {
                "es": "Pancakes Esponjosos"
            },
            "description": {},
            "price": 6900
        },
        {
            "id": "chk-base-waffles",
            "category": "base",
            "active": true,
            "name": {
                "es": "Waffles Artesanales"
            },
            "description": {},
            "price": 5900
        },
        {
            "id": "chk-prot-lomo",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Dados de Lomo de Res"
            },
            "description": {},
            "price": 12900
        },
        {
            "id": "chk-prot-pollo",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Pechuga de Pollo al Grill"
            },
            "description": {},
            "price": 9900
        },
        {
            "id": "chk-prot-cerdo",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Julianas de Cerdo",
                "en": "",
                "fr": ""
            },
            "description": {
                "es": "",
                "en": "",
                "fr": ""
            },
            "price": 9900
        },
        {
            "id": "chk-salsa-bolognesa",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Bolognesa de la Casa"
            },
            "description": {},
            "price": 8900
        },
        {
            "id": "chk-prot-huevos",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Huevos Fritos"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-prot-revueltos",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Huevos Revueltos Suaves"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-prot-salchicha",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Huevos con Salchicha"
            },
            "description": {},
            "price": 6300
        },
        {
            "id": "chk-prot-maiz",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Huevos con Maíz Tierno"
            },
            "description": {},
            "price": 5700
        },
        {
            "id": "chk-prot-poche",
            "category": "proteina",
            "active": true,
            "name": {
                "es": "Huevos Poché"
            },
            "description": {},
            "price": 5200
        },
        {
            "id": "chk-salsa-pomodoro",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Pomodoro Napolitana"
            },
            "description": {},
            "price": 3800
        },
        {
            "id": "chk-salsa-champinon",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Cremosa de Champiñones"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-salsa-quesos",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Fondo de Quesos Fundidos"
            },
            "description": {},
            "price": 4600
        },
        {
            "id": "chk-salsa-hogao",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Hogao / Salsa Criolla"
            },
            "description": {},
            "price": 3900
        },
        {
            "id": "chk-salsa-yogurt",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Yogurt Griego Natural"
            },
            "description": {},
            "price": 4300
        },
        {
            "id": "chk-salsa-frutos",
            "category": "salsa",
            "active": true,
            "name": {
                "es": "Reducción de Frutos Rojos"
            },
            "description": {},
            "price": 4500
        },
        {
            "id": "chk-acomp-campesino",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Porción de Queso Fresco"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-prot-mozzarella",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Porción de Queso Mozzarella"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-prot-chorizo",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Rodajas de Chorizo de cerdo"
            },
            "description": {},
            "price": 5800
        },
        {
            "id": "chk-acomp-ensalada",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Ensalada de la Casa"
            },
            "description": {},
            "price": 5300
        },
        {
            "id": "chk-acomp-pantostado",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Tajadas de Pan Tostado"
            },
            "description": {},
            "price": 3500
        },
        {
            "id": "chk-acomp-tocineta",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Tocineta Crujiente"
            },
            "description": {},
            "price": 5800
        },
        {
            "id": "chk-acomp-fruta",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Porción de Fruta de Temporada"
            },
            "description": {},
            "price": 5300
        },
        {
            "id": "chk-acomp-criollas",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Papas Criollas Fritas"
            },
            "description": {},
            "price": 5200
        },
        {
            "id": "chk-acomp-cascos",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Cascos de Papas Fritas"
            },
            "description": {},
            "price": 5500
        },
        {
            "id": "chk-acomp-francesa",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Papas a la Francesa Clásicas"
            },
            "description": {},
            "price": 5500
        },
        {
            "id": "chk-acomp-pure",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Puré de Papa Aterciopelado"
            },
            "description": {},
            "price": 5800
        },
        {
            "id": "chk-acomp-sabaneras",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Rodajas de Sabaneras Asadas"
            },
            "description": {},
            "price": 5000
        },
        {
            "id": "chk-acomp-caldo",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Caldo de Pollo"
            },
            "description": {},
            "price": 12000
        },
        {
            "id": "chk-acomp-cremapollo",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Crema de Pollo y Champiñones"
            },
            "description": {},
            "price": 12000
        },
        {
            "id": "chk-acomp-bowl",
            "category": "acompanamiento",
            "active": true,
            "name": {
                "es": "Bowl Saludable"
            },
            "description": {},
            "price": 12000
        },
        {
            "id": "chk-bebida-cafe",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Café Negro"
            },
            "description": {},
            "price": 3800
        },
        {
            "id": "chk-bebida-chocolate",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Chocolate Espumoso"
            },
            "description": {},
            "price": 4900
        },
        {
            "id": "chk-bebida-panela",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Agua'e panela Tradicional"
            },
            "description": {},
            "price": 4500
        },
        {
            "id": "chk-bebida-latte",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Café Latte"
            },
            "description": {},
            "price": 4900
        },
        {
            "id": "chk-bebida-chai",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Chai Latte Aromático"
            },
            "description": {},
            "price": 6900
        },
        {
            "id": "chk-bebida-matcha",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Matcha Latte"
            },
            "description": {},
            "price": 7900
        },
        {
            "id": "chk-bebida-cocoa",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Cocoa Cremosa"
            },
            "description": {},
            "price": 5900
        },
        {
            "id": "chk-bebida-infusion",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Infusiones Aromáticas"
            },
            "description": {},
            "price": 4800
        },
        {
            "id": "chk-bebida-limonada",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Limonada Cítrica Natural"
            },
            "description": {},
            "price": 5900
        },
        {
            "id": "chk-bebida-jamaica",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Agua de Jamaica"
            },
            "description": {},
            "price": 5500
        },
        {
            "id": "chk-bebida-jugoagua",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Jugo Natural en Agua"
            },
            "description": {},
            "price": 5900
        },
        {
            "id": "chk-bebida-jugoleche",
            "category": "bebida",
            "active": true,
            "name": {
                "es": "Jugo Natural en Leche"
            },
            "description": {},
            "price": 6900
        }
    ],
    "combos": [
        {
            "id": "combo-1",
            "active": true,
            "name": {
                "es": "1. Crepe de la Casa Especial"
            },
            "description": {},
            "items": [
                "chk-base-crepe",
                "chk-prot-pollo",
                "chk-salsa-champinon",
                "chk-acomp-cascos",
                "chk-acomp-ensalada",
                "chk-bebida-jamaica"
            ],
            "regularPrice": 36900,
            "discountPrice": 25800
        },
        {
            "id": "combo-2",
            "active": true,
            "name": {
                "es": "2. Pancakes Deluxe"
            },
            "description": {},
            "items": [
                "chk-base-pancakes",
                "chk-prot-huevos",
                "chk-prot-chorizo",
                "chk-prot-mozzarella",
                "chk-salsa-yogurt",
                "chk-salsa-frutos",
                "chk-acomp-fruta",
                "chk-bebida-chocolate"
            ],
            "regularPrice": 41300,
            "discountPrice": 28900
        },
        {
            "id": "combo-3",
            "active": true,
            "name": {
                "es": "4. Spaghetti Italiano Clásico",
                "en": "",
                "fr": ""
            },
            "description": {
                "es": "",
                "en": "",
                "fr": ""
            },
            "items": [
                "chk-base-pasta",
                "chk-salsa-bolognesa",
                "chk-acomp-francesa",
                "chk-bebida-infusion"
            ],
            "regularPrice": 25200,
            "discountPrice": 17600
        },
        {
            "id": "combo-4",
            "active": true,
            "name": {
                "es": "5. Papas Belgas con Toppings"
            },
            "description": {},
            "items": [
                "chk-base-papasbelgas",
                "chk-prot-cerdo",
                "chk-acomp-tocineta",
                "chk-salsa-quesos",
                "chk-bebida-limonada"
            ],
            "regularPrice": 35000,
            "discountPrice": 24500
        },
        {
            "id": "combo-5",
            "active": true,
            "name": {
                "es": "3. Omelette especial"
            },
            "description": {},
            "items": [
                "chk-base-omelette",
                "chk-prot-pollo",
                "chk-prot-mozzarella",
                "chk-prot-chorizo",
                "chk-bebida-chocolate"
            ],
            "regularPrice": 30400,
            "discountPrice": 21300
        }
    ]
};
